# Both rdkresidentapp and residentui uses same repo.
PV:pn-rdkresidentapp = "4.6.1"
PR:pn-rdkresidentapp = "r0"
SRCREV:pn-rdkresidentapp = "859a3ac2eeec3480703166a67028aa44b7e696ea"
PACKAGE_ARCH:pn-rdkresidentapp = "${APP_LAYER_ARCH}"

PV:pn-residentui = "4.6.1"
PR:pn-residentui = "r0"
SRCREV:pn-residentui = "859a3ac2eeec3480703166a67028aa44b7e696ea"
PACKAGE_ARCH:pn-residentui = "${APP_LAYER_ARCH}"

PV:pn-dab-adapter = "0.7.0"
PR:pn-dab-adapter = "r0"
SRCREV:pn-dab-adapter = "ccfa32fc41126ed320b903b7a7cf468e98984f8a"
PACKAGE_ARCH:pn-dab-adapter = "${APP_LAYER_ARCH}"

PV:pn-mosquitto = "2.0.14"
PR:pn-mosquitto = "r0"
SRCREV:pn-mosquitto = ""
PACKAGE_ARCH:pn-mosquitto = "${APP_LAYER_ARCH}"

PV:pn-dlt-daemon = "2.18.8"
PR:pn-dlt-daemon = "r0"
SRCREV:pn-dlt-daemon = "6a3bd901d825c7206797e36ea98e10a218f5aad2"
PACKAGE_ARCH:pn-dlt-daemon = "${APP_LAYER_ARCH}"
